### PR TITLE
Add ssl option

### PR DESCRIPTION
**Pull request by bialad**
I added a configuration option for non-ssl broker connections, if that's something you are interested in adding.

### CODE REVIEW

**Comment by molobrakos** [comment]
Maybe solved by https://github.com/molobrakos/tellsticknet/commit/489e8bec85f12b9cb8a508e0507dbd57168751ab

**Comment by molobrakos** [comment]
Please reopen if this still does not work

**Comment by bialad** [comment]
I had to change the line to this to get it to work:

**Comment by molobrakos** [comment]
Solved here https://github.com/molobrakos/tellsticknet/commit/ed918b2c5e583a355291a2f76fd528b9f6c15669

**Pull request closed without merging**
